version: "3.9"

services:
  django_app:
    build:
      context: .
    container_name: django_app
    volumes:
      - .:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    environment:
      POSTGRES_DB: educational_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: educational_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d   # mount your custom conf from ./nginx/
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - django_app

volumes:
  postgres_data:
  static_volume:
  media_volume:
