services:
  django_app:
    build: .
    command: gunicorn AtoZ.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - django_volume:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8001:8001"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: educational_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - nginx_conf_volume:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - django_app

volumes:
  postgres_data:
  static_volume:
  media_volume:
  django_volume:
  nginx_conf_volume:
