name: CI/CD Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-lint-format-build:
    name: Test, Lint, Format, Build & Push
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dev requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt

      - name: Run Django tests
        run: docker-compose run --rm django_app python manage.py test

      - name: Lint with flake8
        run: docker-compose run --rm django_app flake8

      - name: Auto-format code (black & isort)
        run: docker-compose run --rm django_app sh -c "black . && isort ."

      - name: Build Docker image
        run: docker-compose build

      - name: Push Docker image to Docker Hub
        run: |
          docker tag educational_platform-django_app ${{ secrets.DOCKER_HUB_USER }}/educational_platform:latest
          docker push ${{ secrets.DOCKER_HUB_USER }}/educational_platform:latest
