name: Test, Lint, Format, Build & Push

on:
  push:
    branches:
      - main

jobs:
  test-lint-build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt

      - name: Run Tests
        run: docker-compose run --rm django_app python manage.py test

      - name: Run Lint
        run: docker-compose run --rm django_app flake8

      - name: Run Format Check
        run: docker-compose run --rm django_app black --check .

      - name: Build Docker Image
        run: docker-compose build

      - name: Push Docker Image
        run: docker-compose push
